

class ErrorCode:
    ACCOUNT_NOT_FOUND = "ACCOUNT_NOT_FOUND"

    class Transfer:
        AMOUNT_EXCEEDED = "AMOUNT_EXCEEDED"
        BAD_SRC_ACCOUNT_NUMBER = "BAD_SRC_ACCOUNT_NUMBER"
        BAD_DST_ACCOUNT_NUMBER = "BAD_DST_ACCOUNT_NUMBER"
